bucket = "ntonthat-apple-health-data"
tz = "Australia/Melbourne"
latest_parquet_file_path = "outputs/"
parquet_file_name = "health.parquet"
repo_parquet_file_path = "data/"
calendar_name = "apple-health-calendar.ics"
column_mapping_file = "config/column_mapping.yaml"
