name: 'health_analytics'
version: '1.0.0'
config-version: 2

profile: 'health_analytics'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

vars:
  s3_bucket: "{{ env_var('S3_BUCKET_NAME') }}"
  squat_exercise_name: "Squat (Barbell)"
  bench_exercise_name: "Bench Press (Barbell)"
  deadlift_exercise_name: "Sumo Deadlift"

models:
  health_analytics:
    # Staging: Views that read from S3 landing/
    staging:
      +materialized: view
      +schema: staging

    # Intermediate: Views for business logic
    intermediate:
      +materialized: view
      +schema: intermediate

    # Marts: External tables written to S3 transformed/
    marts:
      +materialized: external
      +location: "transformed/{{ name }}"
      +format: parquet
