hevy_transforms:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DBT_DUCKDB_PATH', 'hevy.duckdb') }}"
      extensions:
        - httpfs
        - parquet
      settings:
        s3_region: "{{ env_var('AWS_DEFAULT_REGION', 'ap-southeast-2') }}"
        s3_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
      external_root: "s3://{{ env_var('S3_BUCKET_NAME') }}"
