hevy_transforms:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DBT_DUCKDB_PATH', 'hevy.duckdb') }}"
      extensions:
        - httpfs
        - parquet
        - delta
      secrets:
        - type: s3
          region: "{{ env_var('AWS_DEFAULT_REGION', 'ap-southeast-2') }}"
          key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
          secret: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
      external_root: "s3://{{ env_var('S3_BUCKET_NAME') }}"
