version: 2

models:
  - name: recent_fct_daily_summary
    description: >
      Last 90 days of fct_daily_summary for fast dashboard reads.
      Same schema as fct_daily_summary, truncated to 90 days.

  - name: recent_fct_workout_sets
    description: >
      Last 365 days of fct_workout_sets for fast dashboard reads.
      Same schema as fct_workout_sets, truncated to 1 year.

  - name: recent_fct_strava_activities
    description: >
      Last 365 days of fct_strava_activities for fast dashboard reads.
      Same schema as fct_strava_activities, truncated to 1 year.
