select
    name,
    sex,
    event,
    equipment,
    age,
    ageclass as age_class,
    birthyearclass as birth_year_class,
    division,
    bodyweightkg as bodyweight_kg,
    weightclasskg as weight_class_kg,
    squat1kg as squat1_kg,
    squat2kg as squat2_kg,
    squat3kg as squat3_kg,
    squat4kg as squat4_kg,
    best3squatkg as best3_squat_kg,
    bench1kg as bench1_kg,
    bench2kg as bench2_kg,
    bench3kg as bench3_kg,
    bench4kg as bench4_kg,
    best3benchkg as best3_bench_kg,
    deadlift1kg as deadlift1_kg,
    deadlift2kg as deadlift2_kg,
    deadlift3kg as deadlift3_kg,
    deadlift4kg as deadlift4_kg,
    best3deadliftkg as best3_deadlift_kg,
    totalkg as total_kg,
    place,
    dots,
    wilks,
    glossbrenner,
    goodlift,
    tested,
    country,
    state,
    federation,
    parentfederation as parent_federation,
    date as metric_date,
    meetcountry as meet_country,
    meetstate as meet_state,
    meettown as meet_town,
    meetname as meet_name,
    sanctioned,
    ctrl_load_date
from
    read_csv(
        's3://{{ var("s3_bucket") }}/landing/exercise/openpowerlifting/*.csv'
    )
