version: 2

sources:
  - name: hevy
    description: Hevy workout tracking app data from dlt landing zone
    meta:
      owner: data-team
      source_type: api
      zone: landing
    tables:
      - name: workouts
        description: Workout sessions from Hevy API
        external:
          location: "s3://{{ var('s3_bucket') }}/landing/hevy/workouts"
          file_format: delta

      - name: exercises
        description: Exercises within workouts
        external:
          location: "s3://{{ var('s3_bucket') }}/landing/hevy/workouts__exercises"
          file_format: delta

      - name: sets
        description: Individual sets within exercises
        external:
          location: "s3://{{ var('s3_bucket') }}/landing/hevy/workouts__exercises__sets"
          file_format: delta

  - name: apple_health
    description: Apple Health metrics from dlt landing zone
    meta:
      owner: data-team
      source_type: s3_export
      zone: landing
    tables:
      - name: health_metrics
        description: Flattened health metrics from Apple Health JSON exports
        external:
          location: "s3://{{ var('s3_bucket') }}/landing/health/health_metrics"
          file_format: delta

  - name: strava
    description: Strava activity data from dlt landing zone
    meta:
      owner: data-team
      source_type: api
      zone: landing
    tables:
      - name: activities
        description: Activities from Strava API (runs, rides, swims, etc.)
        external:
          location: "s3://{{ var('s3_bucket') }}/landing/strava/activities"
          file_format: delta
