version: 2

sources:
  - name: s3_landing
    description: "Raw data ingested into S3 landing zone"
    database: "{{ var('s3_bucket') }}"
    schema: landing
    meta:
      dagster:
        asset_namespace: []
    tables:
      - name: apple_health
        description: "Apple Health metrics data from Auto Health Export app"
        external:
          location: "s3://{{ var('s3_bucket') }}/health/"
          file_format: "json"
        meta:
          dagster:
            asset_key: ["apple_health"]
      - name: hevy
        description: "Workout data from Hevy API"
        external:
          location: "s3://{{ var('s3_bucket') }}/exercise/hevy/"
          file_format: "json"
        meta:
          dagster:
            asset_key: ["hevy"]
      - name: openpowerlifting
        description: "Competition data from OpenPowerlifting"
        external:
          location: "s3://{{ var('s3_bucket') }}/exercise/openpowerlifting/"
          file_format: "csv"
        meta:
          dagster:
            asset_key: ["openpowerlifting"]
