version: 2

sources:
  - name: s3_landing
    description: "Raw data ingested into S3 landing zone"
    meta:
      dagster:
        asset_namespace: []
    tables:
      - name: apple_health
        description: "Apple Health metrics data from Auto Health Export app"
        meta:
          dagster:
            asset_key: ["apple_health"]
        config:
          external_location: "s3://{{ var('s3_bucket') }}/landing/health/*.json"
          options:
      - name: hevy
        description: "Workout data from Hevy API"
        meta:
          dagster:
            asset_key: ["hevy"]
        config:
          external_location: "s3://{{ var('s3_bucket') }}/landing/exercise/hevy/*.json"
      - name: openpowerlifting
        description: "Competition data from OpenPowerlifting"
        meta:
          dagster:
            asset_key: ["openpowerlifting"]
        config:
          external_location: "s3://{{ var('s3_bucket') }}/landing/exercise/openpowerlifting/*.csv"
